#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportSutherland \
               constant/reactions constant/thermo.STM

runApplication blockMesh
runApplication setFields

decomposePar
mpirun -np 4 "$application" -parallel
reconstructPar
#------------------------------------------------------------------------------
